security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:

    dev:
      security: false

    main:
      provider: app_user_provider
      lazy: true
      user_checker: App\Security\UserChecker
      stateless: false

      form_login:
        login_path: login
        check_path: login
        username_parameter: email
        password_parameter: password
        enable_csrf: true
        default_target_path: home
        post_only: true

      logout:
        path: logout
        target: login

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER

  access_control:
    # Login / Register → publics
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }

    # Gestion admin complète
    - { path: ^/admin, roles: ROLE_ADMIN }

    # Toutes les autres routes nécessitent connexion
    - { path: ^/, roles: ROLE_USER }
